# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "XXIII Congresso Nacional da Ordem DeMolay - 11 e 12 Novembro - Teresina, Piauí"
email: "organizacao@23cnod.com"
description: "Participe do XXIII Congresso Nacional da Ordem DeMolay que ocorrerá nos dias 11 e 12 de Novembro de Teresina-PI"
baseurl: ""
url: "http://localhost:4000"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Secretário do Congresso"
organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "organizacao@23cnod.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "23, cnod, demolay, brasil, piaui, teresina"
twitterAccount: "@23CNOD"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/programacao/", text: "Programação"}
 - {permalink: "/capitulo-luiz-neto/", text: "Capítulo Luiz Neto"}
 - {permalink: "/equipe/", text: "Equipe"}
 - {permalink: "/logistica/", text: "Logística"}
 
bottomNavigationLinks:
 - {permalink: "/#tickets", text: "Inscreva-se"}
rightNavigationButtons:
 - {permalink: "/#tickets", text: "Inscreva-se"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "XXIII CNOD - <typeout>"
eventDate: "Teresina, 11 e 12 de Novembro, 2016"
typeoutTextValues: '"Amor Filial", "Cortesia", "Companherismo", "Fidelidade", "Pureza", "Patriotismo"'
typeoutFallback: "Teresina"
heroButtons:
 - {permalink: "/#tickets", text: "Faça sua inscrição"}

# About Block
aboutTitle: "Sobre XXIII CNOD"
aboutBlock:
 - {title: "Abertura dos sonhos", image: "conference.jpg", text: "Nosso objetivo, ao propor a organização do CNOD 2016, era fazer algo totalmente diferente e inovador. Quebra paradigmas. Revolucionar o modo de se pensar os Congressos DeMolay. Para fazer jus a esse objetivo, convidamos você para se programar em NÃO PERDER a Abertura do Congresso Nacional, a se realizar na noite da sexta-feira, 11 de novembro de 2016. Serão tantas surpresas e emoções... Você nunca mais participará de Aberturas da mesma forma!" }
 - {title: "Expo Nacional", image: "workshop.jpg", text: "Uma enorme exposição interativa de projetos de vários Capítulos de todo o Brasil para você apresentar como se faz a Ordem DeMolay no seu Capítulo e aprender como ela é feita pelo Brasil afora. Os projetos também serão avaliados para premiação do mais interessante, de acordo com os parâmetros propostos." }
 - {title: "Mostra Cultural Piauiense", image: "workshop.jpg", text: "Os Capítulos da Ordem DeMolay Piauiense, em conjunto com outras organizações paramaçônicas juvenis, irão expor traços da cultura local, envolvendo turismo, culinária, artesanato e arte. Nessa ocasião serão distribuídos brindes e vendidos alguns objetos culturais." }
 - {title: "Torneio Frank Marshall de Ritualística", image: "workshop.jpg", text: "Está confirmado também o Torneio Nacional de Ritualística, agora com uma nova roupagem. Para quem ama Ritualística e não perde um desafio, o Torneio será INESQUECÍVEL!" }
 - {title: "Assembleia Geral do SCODB e da Alumni Brasil", image: "workshop.jpg", text: "Como de costume, haverá a Assembleia Geral Ordinária do Supremo Conselho da Ordem DeMolay para o Brasil, ocasião em que a atual gestão irá fazer um balanço final de suas atividades e deliberaremos sobre os rumos de nossa instituição para o ano de 2017. A Associação DeMolay Alumni Brasil também realizará, nessa ocasião, seu encontro atual para decidir o destino da associação." }
 - {title: "Turismo", image: "workshop.jpg", text: "Para encantar você de vez com o Piauí, está CONFIRMADO um passeio extra ao litoral piauiense que, apesar de ser um dos menores do nordeste, é considerado um dos mais belos e tranquilos! Então, programe-se para aproveitarmos no domingo (13) e na segunda (14) esse passeio, já que a terça (15) é feriado nacional. Dessa forma, se tiver interesse em curtir o litoral conosco, agende sua passagem de volta ao Estado somente para terça-feira (15), a partir das 15h. Mais informações sobre valores reservas estão disponíveis em breve!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "400", specialCharacter: "+", info: "participantes", detail: "de todo o Brasil"}
 - {count: "48", specialCharacter: "+", info: "horas de pura interação DeMolay", detail: "no calor fraterno do Piauí"}
 - {count: "1", specialCharacter: "+", info: "abertura", detail: "INESQUECÍVEL!!"}

# Latest News Block
latestNewsTitle: "Últimas notícias"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Palestrantes"
rockstarSpeakersButtonText: "Veja todos palestrantes"

# Social Media Block
socialMediasImage: "social-media.jpg"
socialMediasCount: 3
socialMediasTitle: "Acompanhe"
socialMediasButtonText: ""

# Location Block
locationBlockTitle: "Localização"
eventLocationName: "Blue Tree Towers Rio Poty Hotel"
eventLocationLink: "http://www.bluetree.com.br/hotel/blue-tree-towers-rio-poty/"
eventStreetAddress: "Av. Mal. Castelo Branco, 555 - Ilhotas"
eventAddressLocality: "Teresina"
eventAddressLocalityRegion: "Piauí"
eventPostalCode: "64014058"
eventAddressCountry: "Brasil"
eventStartTime: "2016-10-24T10:00"
eventDoorTime: "09:00"
eventEndTime: "2016-10-25T20:00"
eventPlaceCoordinates: "-5.0873815, -42.7961361"
mapCenterCoordinates: "-5.0873815, -42.7961361"
mapMobileCenterCoordinates: "-5.0873815, -42.7961361"

# Venue Block
venueBlockTitle: "Ponto de encontro"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Auditório Samambaia"
venueFeatures: ["3 telões", "Sistema de aúdio Doulby Digital Surround EX", "Localizado próximo ao Rio Poty"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "E aí?"
twitterHashTag: "23CNOD"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Parceiros"
partnersC4sponsorsButton: "Seja um patrocinador"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Preços"
ticketsInfo: "Todos as entradas garantem o acesso a toda programação do evento, coffee breakes, almoços e hospedagem no hotel."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "R$"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Compre agora"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Última Chance"
  price: "450"
  priceCurrency: "R$"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Compre agora"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "DeMolay"
  price: "200"
  priceCurrency: "R$"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Compre agora"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=23CNOD", icon: "twitter"}
 - {link: "https://facebook.com/23", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://demolaypi.org.br/", text: "DeMolay Piauí"}
   - {link: "http://demolay.org.br/", text: "SCODB"}
   - {link: "http://sisdm.demolay.org.br/Index.action", text: "SISDM"}
 -
  title: "Contatos"
  links:
   - {link: "mailto:organizacao@23cnod.com", text: "organizacao@23cnod.com"}

# Blog
blogTitle: "Últimas notícias"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre nós"
aboutUs: "O time de organização do XXIII Congresso Nacional divide as tarefas para otimizá-las, mas é uma família só! Mais do que Irmãos, somos amigos de longa data, já trabalhamos juntos na organização de diversos eventos e temos muitas ideias interessantes para colocar em prática. Aliás, mais do que ideias, agimos para isso! Saiba quem está dedicando suas noites de sonho para realizar o Congresso dos sonhos e, em caso de necessidade, contate-nos!"

# Logistics Find Way Block
findWayTitle: "Encontre seu caminho"
findWayDistance: "Distância"
findWayDriving: "Dirigindo"
findWayWalking: "Caminhando"
findWayBicycling: "Bicicleta"
findWayTransit: "Trânsito"
findWayFindFlight: "Encontre um vôo"
logisticsMapCenterCoordinates: "-5.0873815, -42.7961361"
logisticsMapMobileCenterCoordinates: "-5.0873815, -42.7961361"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Comece ao redor de Teresina"
directionDetailsCards:
 - {title: "Do aeroporto", information: 'Aeroporto está à esquerda da cidade. É facilmente acessível por carro, transporte público ou táxi. Mais informações estão disponíveis no <a href="http://www.infraero.gov.br/index.php/aeroportos/piaui/aeroporto-de-teresina.html">site do aeroporto</a>.'}
 - {title: "Hoteil Oficial", information: 'Velit Hotel <br/> Endereço: Av. dos Ipês, 382 - São João <br/> Telefone: 86 3233-4878 <br/> E-mail para reservas: Tarifas promocionais: '}
 - {title: "Alojamento Tour", information: 'Dentro de poucos dias confirmaremos o local que servirá de alojamento, suas instalações e valor simbólico que será cobrado'}
directionDetailsWideCards:
 -
  title: "Dúvidas?"
  subCards:
   -
    title: "Hóteis"
    links:
     - {link: "http://www.metropolitanhotel.com.br/", text: "Metropolitan Hotel"}
     - {link: "http://www.bluetree.com.br/hotel/blue-tree-towers-rio-poty/", text: "Blue Tree Towers Rio Poty Hotel"}
   -
    title: "Credenciamento"
    links:
     - {link: "http://www.bluetree.com.br/hotel/blue-tree-towers-rio-poty/", text: "Blue Tree Towers Rio Poty Hotel"}
   -
    title: "Entretenimento"
    links:
     - {link: "https://www.google.com.br/maps/search/pontos+tur%C3%ADsticos+perto+de+Teresina+-+PI/@-5.056354,-42.8136517,14z?hl=pt-BR", text: "Pontos Turísticos"}
     - {link: "https://www.google.com.br/maps/search/pubs+Teresina+-+PI/@-5.0562681,-42.8136517,14z/data=!3m1!4b1?hl=pt-BR", text: "Pubs"}
     - {link: "https://www.google.com.br/maps/search/restaurantes+Teresina+-+PI/@-5.0726093,-42.7913046,13.83z/data=!4m3!2m2!5m1!4e3?hl=pt-BR", text: "Restaurantes"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "Veja no Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
